### ISSUE TITLE
REFORGER v1.1 COMPATIBILITY

### ISSUE THREAD

**Issue by TheWireLord** [ArmaOverthrow/Overthrow.Arma4#37]
**Looks like the latest updated of Reforger to v 1.1 has caused the Overthrow mod to break on startup.**

Crash log:

`---------------------------------------------
Log  started at 2024-03-13 15:49:10 (2024-03-13 19:49:10 UTC)
------------------------------------
13.03 2024 15:49:10
Can't compile "Game" script module!
Scripts/Game/GameMode/Managers/Factions/OVT_ResistanceFactionManager.c(67): Unexpected statement 'ref'
Runtime mode`

**Comment by TheWireLord** [comment]
FIXED WITH LATEST COMMIT!

**COMMIT**: `Reforger 1.1 compile errors`

Thank you for your hard work @armazac <3

**Comment by armazac** [comment]
Still some issues with 1.1 that will be addressed this week, only compile errors have been fixed

**Comment by zigi2020** [comment]
not fixed, getting same error now with CRX AI mod. Unexpected statement 'ref' tons of other mods are causing same error
